### ISSUE TITLE
Watching?

### ISSUE THREAD

**Issue by curran** [martpie/next-plugin-transpile-modules#5] opened 2018-11-22 13:04 UTC
It would be awesome if changes made in transpiled packages were to cause the same automatic reloading as files changed within the `/pages` directory. It appears this case is considered in the plugin implementation, and has been iterated on in [recent changes](https://github.com/martpie/next-plugin-transpile-modules/commit/958472c0b9a4eb47599dfed4798bc1c05b74b072), but it is not working for me.

I have a reproduction case here: https://github.com/curran/nextjs-esm-example/pull/4

Reproduction specifics:

 * Uses NextJS 7
 * Uses Lerna (symlinks)
 * Uses an Express app that invokes Next

Desired behavior:

 * The NextJS dev server should reload when you change files in the transpiled package.

Current behavior:

 * The NextJS dev server does not reload when you change files in the transpiled package (but it does reload if you change files locally).

I notice there's already something going on with `watchOptions` at https://github.com/martpie/next-plugin-transpile-modules/blob/master/index.js#L59, but I don't know enough about Webpack to assess why the reloading would not be working here.

I can confirm the `webpackDevMiddleware` is in fact getting set up, and the regex has been replaced.

`console.log(ignored);` from within the plugin yields the following:

```
[ /\.git/,
  /\.next\//,
  /node_modules(?!\/(some-es6-package)(?!.*node_modules))/ ]
```

Still, when I change a file inside `/node_modules/some-es6-package/`, the watcher does not catch the change.

P. S. Thanks for maintaining this plugin! It's super useful.

**Comment by curran** [comment] 2018-11-22 13:35
Also tested the official example, and can confirm that watching is not happening with that example also https://github.com/zeit/next.js/tree/canary/examples/with-yarn-workspaces

**Comment by martpie** [comment] 2018-11-26 02:30
Out of curiosity, why using Lerna?

Also If you use yarn (without workspaces), this plugin won’t work because `yarn install` copy files instead of symlinking them.

**Comment by martpie** [comment] 2018-11-26 02:34
If what I said do not help, could you show me a repo where it is reproducible, so I can debug it?

**Comment by martpie** [comment] 2018-11-26 14:55
I am going to checks, maybe it is a bug with the plugin.

You can also have a look at what Lerna's creator told me a few months ago: https://github.com/lerna/lerna/issues/1243#issuecomment-401396850

**Comment by curran** [comment] 2018-11-27 09:34
Thanks for the thread link! It is very interesting. Perhaps Lerna is not the right choice for me after all.

The main reason actually I'm using it is to establish an explicit dependency graph between internal packages. Meaning, to make sure certain packages are isolated and do not import from certain others (following [Clean Architecture](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html) principles). But, maybe what I want to do does not require Lerna. I'm not sure.

Thanks again for the link, and for looking into this.

**Comment by martpie** [comment] 2018-11-27 13:53
Just tested it, everything is working fine :) 

A problem with Node.js? I tested with Node v8.11.3.

![transp](https://user-images.githubusercontent.com/1311607/49086108-0a5f6a00-f254-11e8-86c3-2b3d64868298.gif)

**Comment by zachariahtimothy** [comment] 2018-11-28 16:41
@martpie thanks so much for sharing. I am following @curran 's esm example but I am using typescript. This plugin is re-transpiling as expected but I still have to manually restart the Next JS app (when changes are made to dependent lib). Any ideas on how to get next to restart automatically when a dependent TS/TSX file is changed? Thanks!

**Comment by zachariahtimothy** [comment] 2018-11-28 17:03
Thank you for sharing @martpie ! I am going to try this with Lerna and Yarn since Lerna uses symlinks. Would you like a PR if I get that working?

**Comment by martpie** [comment] 2018-11-28 17:39
As said earlier in this issue, [Lerna is not a tool to manage dependencies](https://github.com/martpie/next-plugin-transpile-modules/issues/5#issuecomment-441666854) between projects, but a tool to publish multiple packages to npm :)

This monorepo example I gave you is the fruit of countless hours to make this setup work simply and correctly (I went through the Lerna thing too, `next-plugin-transpile-modules`’s fork was a part of it as well)

If you are talking about a PR to the monorepo example, I am not interested in having Lerna working as it is not it’s puepose.

If you are talking about this Next.js plugin, and you see I missed something or there’s a bug, yes, I’d gladly appreciate a PR :]

**Comment by zachariahtimothy** [comment] 2018-11-28 17:41
@martpie yes I forgot about that. There is so many people using lerna incorrectly that is gets confusing what it's true purpose. My attempts failed so guess it is back to NPM for me. Thanks again!

**Comment by martpie** [comment] 2018-11-29 08:45
Did you manage to fix this @curran? Can I close this?

**Closed** 2018-12-04 12:18 UTC

**Comment by KingScooty** [comment] 2018-12-06 22:47
I can replicate the issue using the next example (https://github.com/zeit/next.js/tree/canary/examples/with-yarn-workspaces).

The issues seem to have crept in in the canary releases of next. 

Hot reloading is not working with the latest canaryt release of next (`next: ^7.0.2-canary.41`)

**Comment by zachariahtimothy** [comment] 2018-12-07 14:49
All - FWIW, I ended up taking a different approach based on https://github.com/panter/next-workspaces. Both have pros and cons but I really struggled with the idea I would be banned form yarn. It may not be necessary these days but muscle memory and such ;).
